package com.infosupport;

import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import java.io.IOException;

public class QuestionsResource extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        String id = req.getParameter("id");
        System.out.println("GET /questions " + (id != null ? "id=" + id : ""));

        resp.setStatus(201);
        resp.addHeader("Content-Type", "application/json;charset=UTF-8");
        resp.addHeader("Access-Control-Allow-Origin", "http://localhost:4200");
        resp.getWriter().println("""
                  [
                    {
                      "R1": true,
                      "R2": true,
                      "R3": true,
                      "BR": true,
                      "fMinors": true,
                      "fMajors": true,
                      "fSoftball": true,
                      "fLocal": false,
                      "fFed": false,
                      "fIntermediates": true,
                      "fJuniors": true,
                      "fSeniors": true,
                      "fRegular": true,
                      "fTournament": true,
                      "fBaseball": true,
                      "nDiff": 3,
                      "sLocal": null,
                      "cOuts": 0,
                      "cBalls": 0,
                      "cStrikes": 0,
                      "sQuestion": "3rd baseman asks for and gets time.  He confers with the pitcher and returns to 3rd base with the ball.  R3 steps off the bag and is tagged out by the 3rd baseman.",
                      "rgsAnswers": [
                        "R3 is out",
                        "R3 is not out.",
                        null,
                        null
                      ],
                      "nCorrectAnswer": 2,
                      "id": 9,
                      "nGivenAnswer": 0,
                      "iQuestionTarget": 0,
                      "sRuling": "3.12, 5.11. When time is called, the ball is dead.  The ball cannot become live again until the pitcher is set on the mound, with the ball, and umpire calls \\"play\\".",
                      "sLastRulebookChecked": "2007"
                    },
                    {
                      "R1": false,
                      "R2": true,
                      "R3": false,
                      "BR": true,
                      "fMinors": true,
                      "fMajors": true,
                      "fSoftball": true,
                      "fLocal": false,
                      "fFed": true,
                      "fIntermediates": true,
                      "fJuniors": true,
                      "fSeniors": true,
                      "fRegular": true,
                      "fTournament": true,
                      "fBaseball": true,
                      "nDiff": 3,
                      "sLocal": null,
                      "cOuts": 0,
                      "cBalls": 0,
                      "cStrikes": 0,
                      "sQuestion": "Runner on 2nd steals third.  The pitch hits the batter and rolls away allowing the runner to continue and score.",
                      "rgsAnswers": [
                        "Ball is live, Batter takes 1st base, R2 scores.",
                        "Ball is dead, Batter takes 1st base, R2 is placed back a 2nd.",
                        null,
                        null
                      ],
                      "nCorrectAnswer": 2,
                      "id": 25,
                      "nGivenAnswer": 0,
                      "iQuestionTarget": 0,
                      "sRuling": "5.09(a). The ball is dead when the batter is hit.  No plays can be made when the ball is dead.",
                      "sLastRulebookChecked": "2007"
                    },
                    {
                      "R1": false,
                      "R2": false,
                      "R3": false,
                      "BR": false,
                      "fMinors": true,
                      "fMajors": true,
                      "fSoftball": true,
                      "fLocal": false,
                      "fFed": true,
                      "fIntermediates": true,
                      "fJuniors": true,
                      "fSeniors": true,
                      "fRegular": true,
                      "fTournament": true,
                      "fBaseball": true,
                      "nDiff": 3,
                      "sLocal": null,
                      "cOuts": 0,
                      "cBalls": 0,
                      "cStrikes": 0,
                      "sQuestion": "Fielder throws the glove at a batted ball but does not touch the ball.",
                      "rgsAnswers": [
                        "Batter is awarded 3 bases.",
                        "Batter is awarded 2 bases.",
                        "Batter is awarded 1 base.",
                        "No penalty"
                      ],
                      "nCorrectAnswer": 4,
                      "id": 32,
                      "nGivenAnswer": 0,
                      "iQuestionTarget": 0,
                      "sRuling": "7.05(b) The fielder must actually touch the ball in order for a penalty to be assessed.",
                      "sLastRulebookChecked": "2007"
                    },
                    {
                      "R1": false,
                      "R2": false,
                      "R3": false,
                      "BR": false,
                      "fMinors": true,
                      "fMajors": true,
                      "fSoftball": true,
                      "fLocal": false,
                      "fFed": true,
                      "fIntermediates": true,
                      "fJuniors": true,
                      "fSeniors": true,
                      "fRegular": true,
                      "fTournament": true,
                      "fBaseball": true,
                      "nDiff": 3,
                      "sLocal": null,
                      "cOuts": 0,
                      "cBalls": 0,
                      "cStrikes": 0,
                      "sQuestion": "Batter hits a line drive over the head of the shortstop.  The shortstop throws his glove in the air and hits the ball with his glove.",
                      "rgsAnswers": [
                        "Each runner is awarded 3 bases",
                        "Each runner is awarded 2 bases",
                        "Each runner is awarded 1 base",
                        "No award"
                      ],
                      "nCorrectAnswer": 1,
                      "id": 33,
                      "nGivenAnswer": 0,
                      "iQuestionTarget": 0,
                      "sRuling": "7.05(c)",
                      "sLastRulebookChecked": "2007"
                    },
                    {
                      "sQuestion": "Batter hits a ball deep to left field.  The left fielder holds his cap up to deflect the ball.  The umpire awards 3 bases.  The left fielder is slow to return the ball, and the batter (now on 3rd) runs home.",
                      "cStrikes": 2,
                      "id": 34
                    },
                    {
                      "R1": true,
                      "R2": false,
                      "R3": true,
                      "BR": false,
                      "fMinors": true,
                      "fMajors": true,
                      "fSoftball": true,
                      "fLocal": false,
                      "fFed": true,
                      "fIntermediates": true,
                      "fJuniors": true,
                      "fSeniors": true,
                      "fRegular": true,
                      "fTournament": true,
                      "fBaseball": true,
                      "nDiff": 3,
                      "sLocal": null,
                      "cOuts": 0,
                      "cBalls": 0,
                      "cStrikes": 0,
                      "sQuestion": "Pitcher, from the pitching position, throws to 1st to catch R1 not standing on 1st.  The throw goes over F3's head and out of play.",
                      "rgsAnswers": [
                        "All runners get 1 base.  R3 scores",
                        "All runners get 2 bases.  R3 scores",
                        "R1 goes to 2nd.  R3 stays on 3rd.",
                        null
                      ],
                      "nCorrectAnswer": 1,
                      "id": 41,
                      "nGivenAnswer": 0,
                      "iQuestionTarget": 0,
                      "sRuling": "7.13(h)  The pitcher was on the pitchers plate, so the runners only get 1 base.  If the pitcher were fielding a ball and made a wild throw to 1st, or if the pitcher had stepped off of the pitchers plate with his pivot foot, 7.13(g) would apply and runners would get 2 bases.",
                      "sLastRulebookChecked": "2007"
                    },
                    {
                      "R1": false,
                      "R2": false,
                      "R3": false,
                      "BR": false,
                      "fMinors": true,
                      "fMajors": true,
                      "fSoftball": true,
                      "fLocal": false,
                      "fFed": true,
                      "fIntermediates": true,
                      "fJuniors": true,
                      "fSeniors": true,
                      "fRegular": true,
                      "fTournament": true,
                      "fBaseball": true,
                      "nDiff": 3,
                      "sLocal": null,
                      "cOuts": 0,
                      "cBalls": 0,
                      "cStrikes": 0,
                      "sQuestion": "Umpire declares \\"Infield Fly, Batter's Out\\", but the fielder drops the ball intentionally.",
                      "rgsAnswers": [
                        "Ball is dead immediately, BR is out",
                        "Ball is live, BR is out",
                        "Ball is live, BR is not out",
                        null
                      ],
                      "nCorrectAnswer": 1,
                      "id": 46,
                      "nGivenAnswer": 0,
                      "iQuestionTarget": 0,
                      "sRuling": "2.00 Infield Fly.  The ball is live and runners may advance (or retouch and advance) as with any fly ball. 6.05(k) allows infield fly to take precedence over an intentionally dropped fly ball on the infield.",
                      "sLastRulebookChecked": "2007"
                    },
                    {
                      "R1": true,
                      "R2": true,
                      "R3": false,
                      "BR": false,
                      "fMinors": true,
                      "fMajors": true,
                      "fSoftball": true,
                      "fLocal": false,
                      "fFed": true,
                      "fIntermediates": true,
                      "fJuniors": true,
                      "fSeniors": true,
                      "fRegular": true,
                      "fTournament": true,
                      "fBaseball": true,
                      "nDiff": 4,
                      "sLocal": null,
                      "cOuts": 2,
                      "cBalls": 0,
                      "cStrikes": 0,
                      "sQuestion": "Batter hits a single, runner on second scores, runner on first base missed 2nd base and reaches third.  The defense properly appeals that he missed second.  Does the run count?",
                      "rgsAnswers": [
                        "Yes",
                        "No",
                        null,
                        null
                      ],
                      "nCorrectAnswer": 2,
                      "id": 49,
                      "nGivenAnswer": 0,
                      "iQuestionTarget": 0,
                      "sRuling": "2.0, 4.09(a).  R1 was forced to 2nd, so the play is a force out.  No runner may score if the 3rd out is a force out.",
                      "sLastRulebookChecked": "2007"
                    },
                    {
                      "R1": true,
                      "R2": true,
                      "R3": false,
                      "BR": false,
                      "fMinors": true,
                      "fMajors": true,
                      "fSoftball": true,
                      "fLocal": false,
                      "fFed": true,
                      "fIntermediates": true,
                      "fJuniors": true,
                      "fSeniors": true,
                      "fRegular": true,
                      "fTournament": true,
                      "fBaseball": true,
                      "nDiff": 3,
                      "sLocal": null,
                      "cOuts": 1,
                      "cBalls": 0,
                      "cStrikes": 0,
                      "sQuestion": "Batter hits a fly ball to the infield in front of 3rd base.  Umpire calls \\"Infield Fly if Fair.\\"  The 3rd baseman lets it drop in foul territory where it bounces fair.  Is the batter out?",
                      "rgsAnswers": [
                        "Yes",
                        "No",
                        null,
                        null
                      ],
                      "nCorrectAnswer": 1,
                      "id": 50,
                      "nGivenAnswer": 0,
                      "iQuestionTarget": 0,
                      "sRuling": "2.00, 6.05(d).  It was a fair ball, so the infield fly rule applies.",
                      "sLastRulebookChecked": "2007"
                    },
                    {
                      "R1": true,
                      "R2": true,
                      "R3": true,
                      "BR": true,
                      "fMinors": true,
                      "fMajors": true,
                      "fSoftball": true,
                      "fLocal": false,
                      "fFed": true,
                      "fIntermediates": true,
                      "fJuniors": true,
                      "fSeniors": true,
                      "fRegular": true,
                      "fTournament": true,
                      "fBaseball": true,
                      "nDiff": 4,
                      "sLocal": null,
                      "cOuts": 2,
                      "cBalls": 0,
                      "cStrikes": 0,
                      "sQuestion": "Batter walks.  Catcher throws ball to first baseman.  The first baseman missed the throw into right field.  All runners score with the batter reaching 2nd.  The defense properly appeals that the batter missed first base.  The umpire agrees and calls the batter out.  How many runs score?",
                      "rgsAnswers": [
                        "3",
                        "2",
                        "1",
                        "0"
                      ],
                      "nCorrectAnswer": 4,
                      "id": 51,
                      "nGivenAnswer": 0,
                      "iQuestionTarget": 0,
                      "sRuling": "4.09(a).  No runs may score if the 3rd out is the result of the batter being put out before touching first.",
                      "sLastRulebookChecked": "2007"
                    },
                    {
                      "R1": true,
                      "R2": false,
                      "R3": false,
                      "BR": true,
                      "fMinors": true,
                      "fMajors": true,
                      "fSoftball": true,
                      "fLocal": false,
                      "fFed": true,
                      "fIntermediates": true,
                      "fJuniors": true,
                      "fSeniors": true,
                      "fRegular": true,
                      "fTournament": true,
                      "fBaseball": true,
                      "nDiff": 3,
                      "sLocal": null,
                      "cOuts": 0,
                      "cBalls": 0,
                      "cStrikes": 0,
                      "sQuestion": "Batter hits a foul fly ball.  The catcher catches the ball and falls into the dugout.  He throws to first before R1 can return to the base.",
                      "rgsAnswers": [
                        "R1 is out",
                        "R1 is allowed to first without liability",
                        "R1 is awarded 2nd base without liability",
                        null
                      ],
                      "nCorrectAnswer": 3,
                      "id": 54,
                      "nGivenAnswer": 0,
                      "iQuestionTarget": 0,
                      "sRuling": "7.04(b) Each runner advances one base when a fielder, after catching a fly ball, falls into a dead ball area.",
                      "sLastRulebookChecked": "2007"
                    }
                  ]
                """);
    }

    @Override
    protected void doDelete(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        resp.setStatus(HttpServletResponse.SC_NO_CONTENT);
    }
}
